### ISSUE TITLE
Mulitple Redis connection from a single verticle

### ISSUE THREAD

**Issue by kvsrikanth** [vert-x/mod-redis#19] opened 2014-05-22 09:15 UTC
Hi,

I am trying to connect to two different redis instances.

I deployed two vertx redis modules with different addresses and different configuration names contains these two redis servers.

It's succesfull intially but with in 5 mins, connection to redis seems dropped and my verticle was not able to query redis....

Any help on this to find out wrong happening...!!

Thanks,,,,

**Comment by pmlopes** [comment] 2015-07-08 17:59
Since I cannot reproduce the issue and there is no concrete code example reproducing the issue i will close this. It can be re-open if an example is provided

**Closed by pmlopes** 2015-07-08 17:59 UTC
